### ISSUE TITLE
Sass/SCSS deprecation warnings: Mixed Declarations

### ISSUE THREAD

**Issue by floehopper** [twbs/bootstrap-rubygem#285] opened 2024-08-13 09:58 UTC
I'm currently seeing a bunch of deprecation warnings for the latest version (v5.3.3) relating to [this Mixed Declarations breaking change in Saas/SCSS](https://sass-lang.com/d/mixed-decls):

```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bootstrap-5.3.3/assets/stylesheets/bootstrap/_reboot.scss
503 │     font-weight: $legend-font-weight;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bootstrap-5.3.3/assets/stylesheets/bootstrap/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bootstrap-5.3.3/assets/stylesheets/bootstrap/_reboot.scss 503:3  @import
    _bootstrap.scss 16:9                                                                                                                 @import
    app/assets/stylesheets/application.scss 2:9                                                                                          root stylesheet
```

**Comment by pkarjala** [comment] 2024-08-22 21:46
Likewise seeing the same in various places; it's a bit annoying as they keep popping up when running tests.

This occurred after changing from `dartsass-sprockets 3.0.0` to `dartsass-sprockets 3.1.0` with a Rails 7.2 upgrade.

**Comment by SebouChu** [comment] 2024-08-26 06:15
Duplicate of https://github.com/twbs/bootstrap/issues/40621, this will be fixed in the next release of Bootstrap

**Closed** 2024-08-26 06:24 UTC
