### ISSUE TITLE
Invalid UTF-8 character in comment

### ISSUE THREAD

**Issue by riddley** [twbs/bootstrap-rubygem#49] opened 2016-08-02 15:22 UTC
https://github.com/twbs/bootstrap-rubygem/blob/master/assets/stylesheets/bootstrap/_tables.scss#L104

in "scheme-dark" the dash is not a dash. Passenger gives me Sass::SyntaxError - Invalid US-ASCII character "\xE2"

**Comment by cvrebert** [comment] 2016-08-09 20:35
Duplicate of https://github.com/twbs/bootstrap/issues/20469

**Closed by cvrebert** 2016-08-09 20:35 UTC
