### ISSUE TITLE
invalid regexp character -ExecJS::RuntimeError

### ISSUE THREAD

**Issue by ashutoshpith** [twbs/bootstrap-rubygem#155] opened 2018-05-17 11:33 UTC
![screenshot 102](https://user-images.githubusercontent.com/31169310/40174801-b579574c-59f3-11e8-9e72-85a0805d8c65.png)
After installing Bootsrap4 it shows that above error,  is Bootsrap4 compatible with rails 5.2 version as bootsrap3 is working fine with that

**Comment by KapilSachdev** [comment] 2018-05-18 14:38
Possible duplicate of #152 and #153. Please try to search for opened issues before creating a new one.
The solution is also listed in the above two issue.
For further information on why its happening (if using duktape) look [here](https://github.com/judofyr/duktape.rb/issues/38).
In case you are not using duktape (default for windows now), this might be something else.

**Closed** 2018-05-19 11:57 UTC
